apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Values.shortName }}-{{ .Values.configMapName }}
  namespace: {{ .Values.global.namespace }}

data:
  application.properties: |+
    {{- $env := .Values.global.env }}
    GLOBAL_ENVIRONMENT={{ $env }}

    {{- range $k, $v := .Values.configmap }}
    {{- if eq (kindOf $v) "map" }}
    {{ $k }}={{ pluck $env $v | first }}
    {{- else }}
    {{ $k }}={{ $v }}
    {{- end }}
    {{- end }}
