services:
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    hostname: 'gitlab.example.com'
    restart: unless-stopped
    ports:
      - '443:443'
      - '80:80'
      - '2222:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      gitlab_net:
        aliases:
          - gitlab


  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './minio:/data'
    networks:
      gitlab_net:
        aliases:
          - minio


  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - './postgres:/var/lib/postgresql/data'
    networks:
      gitlab_net:
        aliases:
          - postgres


networks:
  gitlab_net:
