apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.shortName }}-database
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      {{- toYaml .Values.selectorLabels | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    {{- $cidrs := .Values.networkPolicy.database }}
    {{- $proto := .Values.networkPolicy.databaseProto }}
    {{- $port := .Values.networkPolicy.databasePort }}

    {{ $cidrs_internal := $cidrs }}
    {{ if eq (kindOf $cidrs) "map" }}
    {{ $cidrs_internal = pluck .Values.global.env $cidrs | first }}
    {{ end }}

    {{- range $cidrs_internal }}
    - to:
      - ipBlock:
          cidr: {{ . }}
      ports:
      - protocol: {{ $proto }}
        port: {{ $port }}
    {{- end }}
