refresh:
  property1: Cfg-server value 1 for dev- 37
  property2: Cfg-server value 2 for dev- 37
#  property3: Cfg-server value 3 for dev- 37
  property4: Cfg-server value 4 for dev- 37
app:
  static-env-property: FROM SERVER OVERRIDE dev
