apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: reference-ingress
  namespace: {{ .Values.global.namespace }}

spec:
  rules:
    - host: config.lab.example.com
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.shortName }}-service
                port:
                  number: 8080
            path: /
            pathType: Prefix
