apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.shortName }}-catfact
  namespace: {{ .Values.namespace }}
spec:
  podSelector: { }
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 104.131.8.184/32
      ports:
        - protocol: TCP
          port: 443
    - to:
        - ipBlock:
            cidr: 2604:a880:800:10::1db:5001/128
      ports:
        - protocol: TCP
          port: 443
