apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.shortName }}-service
  namespace: {{ .Values.global.namespace }}

spec:
  selector:
    {{- toYaml .Values.selectorLabels | nindent 4 }}

  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

  type: {{ .Values.service.type }}
