apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.shortName }}-config-client-ext
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      {{- toYaml .Values.selectorLabels | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
