apiVersion: networking.istio.io/v1beta1
kind: Gateway

metadata:
  name: kubelab-gateway
  namespace: {{ .Values.global.namespace }}

spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http-kubelab
        protocol: HTTP
      hosts:
        - "kubelab.lab.example.com"
