apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry

metadata:
  name: catfact-se
  namespace: {{ .Values.global.namespace }}

spec:
  hosts:
    - catfact.ninja
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
