apiVersion: networking.istio.io/v1beta1
kind: VirtualService

metadata:
  name: frontend-vs
  namespace: {{ .Values.global.namespace }}

spec:
  hosts:
    - "kubelab.lab.example.com"
  gateways:
    - kubelab-gateway
  http:
    - route:
        - destination:
            host: kubelab-frontend-service
            port:
              number: 8888
