apiVersion: networking.istio.io/v1beta1
kind: VirtualService

metadata:
  name: nodesrv-vs
  namespace: {{ .Values.global.namespace }}

spec:
  hosts:
    - "kubelab.lab.example.com"
  gateways:
    - kubelab-gateway
  http:
    - match:
        - uri:
            prefix: /node
      route:
        - destination:
            host: kubelab-nodesrv-service
            port:
              number: 8001
