refresh:
  property1: Cfg-server value 1 for local- 37
  property2: Cfg-server value 2 for local- 37
#  property3: Cfg-server value 3 for local- 37
  property4: Cfg-server value 4 for local- 37
app:
  static-env-property: FROM SERVER OVERRIDE loc
app-refresh:
  initial-delay: 15000
  fixed-delay: 7000
